sudo: required
dist: xenial
language: php
php:
  - '7.4'

before_install:
  - ./build/install_dependencies_ubuntu.sh
#  - echo "extension=sqlite3.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - echo "extension=pdo_sqlite.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
# do not build the entire solution; there are windows projects included
#  - dotnet build ./Peachpie.sln

# build the Sdk/compiler:
  - dotnet build ./src/Peachpie.NET.Sdk/

# install NuGets to NuGet cache:
  - dotnet restore ./build/dummy -p:DisableImplicitPeachpieReferences=true

# compile tests:
  - dotnet build ./tests -c Release

script:
  - dotnet test ./src/Tests/Peachpie.Runtime.Tests/Peachpie.Runtime.Tests.csproj
  - dotnet test ./src/Tests/Peachpie.DiagnosticTests/Peachpie.DiagnosticTests.csproj
  - ./build/runtests.sh
