sudo: required
dist: trusty
language: php
php:
  - '7.0'

install: ./build/install_dotnetcore_ubuntu14.sh
script:
  - dotnet restore
  - dotnet build ./src/Compiler/peach/project.json
  - ./tests/runtests.sh